pipeline {
    agent {
        docker {
            image 'node:6-alpine'
            args '-p 3000:3000 --user root'
        }
    }
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                sh 'ping 8.8.8.8 -c 10'
                sh 'npm config set registry https://yarn.npmjs.org'
                sh 'npm install'
            }
        }
        stage('Test') {
            steps {
                sh './jenkins/scripts/test.sh'
            }
        }
        stage('Deliver') {
            steps {
                sh './jenkins/scripts/deliver.sh'
                input message: 'Finished using the web site? (Click Proceed to continue)'
                sh './jenkins/scripts/kill.sh'
            }
        }
    }
}
